import fs from "node:fs";
import path from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { isTerminalState, TaskStateStore } from "../src/task/state.js";
import { cleanup, makeTmpDir } from "./helpers.js";
const dirs:string[]=[]; const make=(pid:(p:number)=>boolean|undefined)=>{const d=makeTmpDir("task-state-lease");dirs.push(d);return new TaskStateStore({stateDir:d,now:()=>new Date("2026-01-02T00:00:00Z"),pidExists:pid});}; afterEach(()=>{while(dirs.length)cleanup(dirs.pop()!);});
describe("Phase 1B lease and transition foundation",()=>{
 it("CASE_WORKSPACE_MUTATION_LEASE_EXCLUSIVE CASE_TWO_MUTATING_TASKS_SERIALIZED CASE_SAME_TASK_DOUBLE_RESUME_BLOCKED_SECOND_OWNER CASE_LEASE_RENEWAL",()=>{const s=make(()=>true),a=s.createTaskState("ws"),b=s.createTaskState("ws"),l=s.acquireWorkspaceMutationLease("ws",a.taskId,"session-a"),o={leaseId:l.leaseId,ownerSessionMarker:"session-a"};expect(()=>s.acquireWorkspaceMutationLease("ws",b.taskId,"session-b")).toThrow(/HELD/);expect(()=>s.acquireWorkspaceMutationLease("ws",a.taskId,"session-b")).toThrow(/HELD/);expect(()=>s.renewWorkspaceMutationLease("ws",a.taskId,{leaseId:l.leaseId,ownerSessionMarker:"wrong"})).toThrow(/NOT_OWNED/);expect(s.renewWorkspaceMutationLease("ws",a.taskId,o).heartbeatAt).toBe("2026-01-02T00:00:00.000Z");expect(s.updateTaskStateUnderMutationLease("ws",a.taskId,0,o,x=>({...x,state:"BUILDING"})).revision).toBe(1);});
 it("stale lease only recovers same dead task and archives before takeover",()=>{const s=make(()=>false),a=s.createTaskState("ws"),b=s.createTaskState("ws"),l=s.acquireWorkspaceMutationLease("ws",a.taskId,"a"),o={leaseId:l.leaseId,ownerSessionMarker:"a"};const renewed=s.renewWorkspaceMutationLease("ws",a.taskId,o);(renewed as any).heartbeatAt="2020-01-01T00:00:00Z";const dir=(s as any).lease("ws");fs.writeFileSync(path.join(dir,"lease.json"),JSON.stringify(renewed));expect(()=>s.takeOverStaleWorkspaceMutationLease("ws",b.taskId,"b",1)).toThrow(/RECOVERY_REQUIRED/);const next=s.takeOverStaleWorkspaceMutationLease("ws",a.taskId,"new",1);expect(next.taskId).toBe(a.taskId);expect(fs.readdirSync(path.dirname(dir)).some((x:string)=>x.startsWith(`.mutation-lease.stale.${l.leaseId}.`))).toBe(true);});
 it("terminal transitions fail closed",()=>{const s=make(()=>true),a=s.createTaskState("ws"),b=s.transitionTask("ws",a.taskId,0,"BLOCKED");expect(isTerminalState("BLOCKED")).toBe(true);expect(()=>s.transitionTask("ws",a.taskId,b.revision,"BUILDING")).toThrow(/ILLEGAL/);});
 it("CASE_LEASE_OWNER_ALIVE_NOT_STALE CASE_WRONG_SESSION_CANNOT_RELEASE_LEASE",()=>{const s=make(()=>true),a=s.createTaskState("ws"),l=s.acquireWorkspaceMutationLease("ws",a.taskId,"a"),o={leaseId:l.leaseId,ownerSessionMarker:"a"};const stale={...l,heartbeatAt:"2020-01-01T00:00:00Z"};fs.writeFileSync(path.join((s as any).lease("ws"),"lease.json"),JSON.stringify(stale));expect(()=>s.takeOverStaleWorkspaceMutationLease("ws",a.taskId,"b",1)).toThrow(/LEASE_NOT_STALE/);expect(()=>s.releaseWorkspaceMutationLease("ws",a.taskId,{leaseId:l.leaseId,ownerSessionMarker:"wrong"})).toThrow(/NOT_OWNED/);s.releaseWorkspaceMutationLease("ws",a.taskId,o);});
 it("CASE_COMPETING_STALE_TAKEOVER_ONLY_ONE_WINS",async()=>{const s=make(()=>false),a=s.createTaskState("ws"),l=s.acquireWorkspaceMutationLease("ws",a.taskId,"old"),dir=(s as any).lease("ws"),stale={...l,heartbeatAt:"2020-01-01T00:00:00Z"};fs.writeFileSync(path.join(dir,"lease.json"),JSON.stringify(stale));const contender=(marker:string)=>new Promise<string>(resolve=>setImmediate(()=>{try{s.takeOverStaleWorkspaceMutationLease("ws",a.taskId,marker,1);resolve("SUCCESS");}catch(error){resolve((error as Error).message);}}));const results=await Promise.all([contender("one"),contender("two")]);expect(results.filter(x=>x==="SUCCESS")).toHaveLength(1);expect(results.filter(x=>/LEASE_NOT_STALE|LEASE_TAKEOVER_RACE/.test(x))).toHaveLength(1);});
 it("CASE_LOCK_ORDERING_NO_INVERSION CASE_LEASE_RENEWAL_NO_STATE_LOCK CASE_NO_STATE_LOCK_DURING_EXTERNAL_WAIT CASE_UPDATE_TASK_STATE_DOES_NOT_ACQUIRE_MUTATION_LEASE CASE_SAME_TASK_DOUBLE_RESUME_NO_DEADLOCK",async()=>{const s=make(()=>true),a=s.createTaskState("ws"),l=s.acquireWorkspaceMutationLease("ws",a.taskId,"a"),o={leaseId:l.leaseId,ownerSessionMarker:"a"},lock=s.acquireTaskStateLock("ws",a.taskId);expect(s.renewWorkspaceMutationLease("ws",a.taskId,o).leaseId).toBe(l.leaseId);s.releaseTaskStateLock(lock);expect(s.updateTaskState("ws",a.taskId,0,x=>({...x,attempt:1})).revision).toBe(1);const contender=()=>new Promise<string>(resolve=>setImmediate(()=>{try{s.updateTaskStateUnderMutationLease("ws",a.taskId,1,o,x=>({...x,attempt:2}));resolve("SUCCESS");}catch(error){resolve((error as Error).message);}}));const results=await Promise.all([contender(),contender()]);expect(results.filter(x=>x==="SUCCESS")).toHaveLength(1);expect(results.filter(x=>x.includes("STALE_TASK_STATE"))).toHaveLength(1);});
});
