import fs from "node:fs";
import path from "node:path";
import { spawn } from "node:child_process";
import { afterEach, describe, expect, it } from "vitest";
import { cleanup, makeTmpDir } from "./helpers.js";
const dirs:string[]=[]; afterEach(()=>{while(dirs.length)cleanup(dirs.pop()!);});
async function killAt(target:string,mode:string){return await new Promise<void>((resolve,reject)=>{const child=spawn(process.execPath,[path.join(process.cwd(),"tests","fixtures","task-state-atomic-child.mjs"),target,mode],{stdio:["ignore","pipe","pipe"],windowsHide:true});let out="";child.stdout.on("data",b=>{out+=b.toString();if(out.includes("READY")){child.kill();}});child.on("exit",()=>resolve());child.on("error",reject);});}
describe("Windows atomic replace admission",()=>{
 it("CASE_WINDOWS_CRASH_DURING_TEMP_WRITE CASE_WINDOWS_NEVER_PARTIAL_JSON",async()=>{const d=makeTmpDir("atomic-win");dirs.push(d);const t=path.join(d,"state.json");fs.writeFileSync(t,JSON.stringify({version:"old"}));await killAt(t,"during-write");expect(JSON.parse(fs.readFileSync(t,"utf8"))).toEqual({version:"old"});});
 it("CASE_WINDOWS_CRASH_BEFORE_RENAME CASE_WINDOWS_TEMP_RESIDUE_NOT_AUTHORITATIVE",async()=>{const d=makeTmpDir("atomic-win");dirs.push(d);const t=path.join(d,"state.json");fs.writeFileSync(t,JSON.stringify({version:"old"}));await killAt(t,"before-rename");expect(JSON.parse(fs.readFileSync(t,"utf8"))).toEqual({version:"old"});});
 it("CASE_WINDOWS_ATOMIC_REPLACE_REPEATED CASE_WINDOWS_TARGET_ALWAYS_OLD_OR_NEW_VALID",async()=>{const d=makeTmpDir("atomic-win");dirs.push(d);const t=path.join(d,"state.json");fs.writeFileSync(t,JSON.stringify({version:"old"}));for(let i=0;i<10;i++){const c=spawn(process.execPath,[path.join(process.cwd(),"tests","fixtures","task-state-atomic-child.mjs"),t,"replace"],{stdio:["ignore","pipe","pipe"],windowsHide:true});let reading:ReturnType<typeof setInterval>|undefined;const observed:string[]=[];await new Promise<void>((resolve,reject)=>{let out="";c.stdout.on("data",b=>{out+=b.toString();if(out.includes("READY")&&!reading){reading=setInterval(()=>{try{observed.push((JSON.parse(fs.readFileSync(t,"utf8")) as {version:string}).version);}catch(error){if(reading)clearInterval(reading);reject(error);}},1);}if(out.includes("RENAMED")){if(reading)clearInterval(reading);resolve();}});c.on("error",reject);c.on("exit",code=>{if(reading)clearInterval(reading);if(code!==0)reject(new Error(`child exited ${code}`));});});expect(observed.length).toBeGreaterThan(0);expect(observed.every(version=>version==="old"||version==="new")).toBe(true);expect(["old","new"]).toContain((JSON.parse(fs.readFileSync(t,"utf8")) as {version:string}).version);}});
});
