import fs from "node:fs";
import path from "node:path";
import { afterEach,describe,expect,it } from "vitest";
import { isTerminalState, TaskStateStore, type MutationLeaseOwner } from "../src/task/state.js";
import { cleanup,makeTmpDir } from "./helpers.js";
const dirs:string[]=[]; const make=()=>{const d=makeTmpDir("task-state");dirs.push(d);return new TaskStateStore({stateDir:d});}; afterEach(()=>{while(dirs.length)cleanup(dirs.pop()!);});

describe("TaskState Phase 1 admission",()=>{
  const owner=(leaseId:string,ownerSessionMarker:string):MutationLeaseOwner=>({leaseId,ownerSessionMarker});
  it("uses leaseId and session marker before taking the task-state lock",()=>{
    const s=make(),task=s.createTaskState("ws"),lease=s.acquireWorkspaceMutationLease("ws",task.taskId,"session-a"),correct=owner(lease.leaseId,"session-a");
    expect(()=>s.updateTaskStateWithMutationLease("ws",task.taskId,owner(lease.leaseId,"session-b"),0,x=>x)).toThrow(/MUTATION_LEASE_NOT_OWNED/);
    expect(s.updateTaskStateWithMutationLease("ws",task.taskId,correct,0,x=>({...x,state:"BUILDING"})).revision).toBe(1);
  });
  it("enforces strict three-state CHECK_BEFORE_REPLAY and blocks Human Gate",()=>{
    const d=makeTmpDir("task-state-replay");dirs.push(d);const now=new Date("2026-01-01T00:00:00.000Z");const s=new TaskStateStore({stateDir:d,now:()=>now});
    const task=s.createTaskState("ws"),lease=s.acquireWorkspaceMutationLease("ws",task.taskId,"session"),o=owner(lease.leaseId,"session");
    const action={actionId:"action",semanticRequestId:"request",validUntil:"2026-01-01T01:00:00.000Z",startedAt:now.toISOString()};
    const active=s.beginActiveAction("ws",task.taskId,0,o,action);
    expect(s.checkBeforeReplay(active,action.validUntil)).toBe("DENY_UNRESOLVED_ACTIVE_ACTION");
    expect(()=>s.transitionTask("ws",task.taskId,active.revision,"HUMAN_GATE")).toThrow(/UNRESOLVED_ACTIVE_ACTION/);
    const resolved=s.resolveActiveAction("ws",task.taskId,active.revision,o,"action");
    expect(s.checkBeforeReplay(resolved,"2025-12-31T23:59:59.000Z")).toBe("DENY_STALE_SEMANTIC_REQUEST");
    expect(s.checkBeforeReplay(resolved,action.validUntil)).toBe("ALLOW");
  });
  it("requires real atomic replacement admission without a fallback",()=>{const s=make();expect(()=>s.assertAtomicReplaceAdmission("ws")).not.toThrow();});
});
describe("TaskState",()=>{it("persists durable random identity",()=>{const s=make(),a=s.createTaskState("ws");expect(a.taskId).toMatch(/^c2c_[0-9a-f]{32}$/);expect(s.readTaskState("ws",a.taskId)).toEqual({status:"VALID",state:a});});it("fails closed for corrupt and IO",()=>{const s=make();expect(s.readTaskState("ws","c2c_none").status).toBe("NOT_FOUND");const f=s.taskFile("ws","c2c_bad");fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,"{");expect(s.readTaskState("ws","c2c_bad").status).toBe("CORRUPT");const io=s.taskFile("ws","c2c_io");fs.mkdirSync(io,{recursive:true});expect(s.readTaskState("ws","c2c_io").status).toBe("IO_ERROR");});it("enforces lock, CAS and transitions",()=>{const s=make(),a=s.createTaskState("ws"),b=s.transitionTask("ws",a.taskId,0,"BUILDING");expect(b.revision).toBe(1);expect(()=>s.transitionTask("ws",a.taskId,0,"BLOCKED")).toThrow(/STALE_TASK_STATE/);const lock=path.join(path.dirname(s.taskFile("ws",a.taskId)),".state-locks",`${a.taskId}.lock`);fs.mkdirSync(lock,{recursive:true});expect(()=>s.updateTaskState("ws",a.taskId,1,x=>x)).toThrow(/TASK_STATE_LOCK_HELD/);fs.rmdirSync(lock);expect(()=>s.transitionTask("ws",a.taskId,1,"DONE")).toThrow(/ILLEGAL_TASK_TRANSITION/);expect(isTerminalState("DONE")).toBe(true);});it("serializes lease and enforces ordering",()=>{const s=make(),a=s.createTaskState("ws"),b=s.createTaskState("ws"),l=s.acquireWorkspaceMutationLease("ws",a.taskId,"x"),o={leaseId:l.leaseId,ownerSessionMarker:l.ownerSessionMarker};expect(()=>s.acquireWorkspaceMutationLease("ws",b.taskId,"y")).toThrow(/WORKSPACE_MUTATION_LEASE_HELD/);expect(s.updateTaskStateWithMutationLease("ws",a.taskId,o,0,x=>({...x,state:"BUILDING"})).revision).toBe(1);expect(()=>s.updateTaskStateWithMutationLease("ws",b.taskId,o,0,x=>x)).toThrow(/MUTATION_LEASE_NOT_OWNED/);s.releaseWorkspaceMutationLease("ws",a.taskId,o);expect(s.acquireWorkspaceMutationLease("ws",b.taskId,"y").taskId).toBe(b.taskId);});it("replaces only complete JSON while readers observe valid state",()=>{const s=make(),a=s.createTaskState("ws");for(let i=0;i<100;i++){expect(s.readTaskState("ws",a.taskId).status).toBe("VALID");s.updateTaskState("ws",a.taskId,i,x=>({...x,attempt:i+1}));}const dir=path.dirname(s.taskFile("ws",a.taskId));fs.writeFileSync(path.join(dir,".crashed.tmp"),"{");expect(s.readTaskState("ws",a.taskId).status).toBe("VALID");expect(fs.readdirSync(dir).filter(x=>x.endsWith(".tmp")).length).toBe(1);});});

describe("Phase 1C acceptance matrix",()=>{
  it("CASE_TASK_ID_PERSISTED CASE_TASK_ID_NOT_REGENERATED_ON_RESUME",()=>{const s=make(),created=s.createTaskState("ws"),resumed=s.readTaskState("ws",created.taskId);expect(resumed).toMatchObject({status:"VALID",state:{taskId:created.taskId}});expect(fs.readdirSync(path.dirname(s.taskFile("ws",created.taskId))).filter(x=>x.endsWith(".json"))).toEqual([`${created.taskId}.json`]);});
  it("CASE_TASK_STATE_NOT_FOUND CASE_TASK_STATE_VALID CASE_CORRUPT_TASK_STATE_FAIL_CLOSED CASE_TASK_STATE_IO_ERROR_FAIL_CLOSED CASE_NO_NEW_TASK_ON_CORRUPT_STATE",()=>{const s=make(),created=s.createTaskState("ws"),dir=path.dirname(s.taskFile("ws",created.taskId));expect(s.readTaskState("ws","c2c_missing").status).toBe("NOT_FOUND");expect(s.readTaskState("ws",created.taskId).status).toBe("VALID");const corrupt=s.taskFile("ws","c2c_corrupt");fs.writeFileSync(corrupt,"{");const before=fs.readdirSync(dir).sort();expect(s.readTaskState("ws","c2c_corrupt").status).toBe("CORRUPT");expect(fs.readdirSync(dir).sort()).toEqual(before);const io=s.taskFile("ws","c2c_io");fs.mkdirSync(io);expect(s.readTaskState("ws","c2c_io").status).toBe("IO_ERROR");});
  it("CASE_ATOMIC_WRITE_NEW_STATE CASE_ATOMIC_REPLACE_EXISTING_STATE CASE_STATE_REVISION_MONOTONIC",()=>{const s=make(),created=s.createTaskState("ws"),file=s.taskFile("ws",created.taskId);expect(JSON.parse(fs.readFileSync(file,"utf8"))).toMatchObject({revision:0});const first=s.updateTaskState("ws",created.taskId,0,x=>({...x,attempt:1})),second=s.updateTaskState("ws",created.taskId,1,x=>({...x,attempt:2}));expect(first.revision).toBe(1);expect(second.revision).toBe(2);expect(JSON.parse(fs.readFileSync(file,"utf8"))).toMatchObject({revision:2,attempt:2});});
  it("CASE_VALID_STATE_TRANSITIONS CASE_INVALID_STATE_TRANSITION_FAIL_CLOSED CASE_DONE_TERMINAL CASE_BLOCKED_TERMINAL CASE_CANCELLED_TERMINAL",()=>{const s=make(),valid=s.createTaskState("ws"),building=s.transitionTask("ws",valid.taskId,0,"BUILDING"),blocked=s.transitionTask("ws",building.taskId,1,"BLOCKED");expect(()=>s.transitionTask("ws",blocked.taskId,2,"BUILDING")).toThrow(/ILLEGAL/);const doneTask=s.createTaskState("ws"),doneBuilding=s.transitionTask("ws",doneTask.taskId,0,"BUILDING"),accepted=s.transitionTask("ws",doneTask.taskId,doneBuilding.revision,"LOCAL_ACCEPTANCE_PASS"),done=s.transitionTask("ws",doneTask.taskId,accepted.revision,"DONE");expect(isTerminalState("DONE")).toBe(true);expect(()=>s.transitionTask("ws",doneTask.taskId,done.revision,"BUILDING")).toThrow(/ILLEGAL/);const cancelledTask=s.createTaskState("ws"),cancelled=s.transitionTask("ws",cancelledTask.taskId,0,"CANCELLED");expect(isTerminalState("CANCELLED")).toBe(true);expect(()=>s.transitionTask("ws",cancelledTask.taskId,cancelled.revision,"BUILDING")).toThrow(/ILLEGAL/);const invalid=s.createTaskState("ws");expect(()=>s.transitionTask("ws",invalid.taskId,0,"DONE")).toThrow(/ILLEGAL/);});
});
