import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { getStateDir } from "../config/paths.js";

/** Valid durable TaskState is orchestration truth; records/conversations are evidence only. */
export const TASK_STATES = ["CREATED","WAIT_FOR_WORKSPACE_MUTATION_LEASE","BUILDING","WAIT_REASONING","CONTRACT_READY","LOCAL_ACCEPTANCE_PASS","WAIT_REVIEW","REVIEW_NEED_CHANGE","REPAIRING","REVIEW_PASS","HUMAN_GATE","DONE","BLOCKED","CANCELLED"] as const;
export type TaskStateName = typeof TASK_STATES[number];
export interface TaskState { taskId:string; workspaceId:string; iteration:number; attempt:number; attemptId:string; reasoningCycle:number; reviewCycle:number; revision:number; state:TaskStateName; createdAt:string; updatedAt:string; activeAction?:ActiveAction; }
export interface ActiveAction { actionId:string; semanticRequestId:string; validUntil:string; startedAt:string; resolvedAt?:string; }
export interface MutationLeaseOwner { leaseId:string; ownerSessionMarker:string; }
export type ReplayDecision = "ALLOW" | "DENY_UNRESOLVED_ACTIVE_ACTION" | "DENY_STALE_SEMANTIC_REQUEST";
export type ProtectedCommandDecision = { decision:"ALLOW"; reason:"READ_ONLY_COMMAND" } | { decision:"DENY"; reason:"EMPTY_OR_UNCLASSIFIED" | "MUTATING_OR_PROTECTED" };
export type ReadTaskState = {status:"NOT_FOUND"}|{status:"VALID";state:TaskState}|{status:"CORRUPT";error:string}|{status:"IO_ERROR";error:string};
export interface WorkspaceMutationLease { workspaceId:string; taskId:string; leaseId:string; ownerPid:number; ownerSessionMarker:string; acquiredAt:string; heartbeatAt:string; }
export interface TaskStateLock { workspaceId:string; taskId:string; ownerPid:number; ownerSessionMarker:string; acquiredAt:string; }
export class TaskStateError extends Error { constructor(public code:string,message=code){super(message);this.name="TaskStateError";} }
export interface TaskStateStoreOptions { stateDir?:string; now?:()=>Date; pidExists?: (pid:number)=>boolean|undefined; }
const terminal=new Set<TaskStateName>(["DONE","BLOCKED","CANCELLED"]);
const edges:Record<TaskStateName,TaskStateName[]>={CREATED:["WAIT_FOR_WORKSPACE_MUTATION_LEASE","BUILDING","BLOCKED","CANCELLED"],WAIT_FOR_WORKSPACE_MUTATION_LEASE:["BUILDING","BLOCKED","CANCELLED"],BUILDING:["WAIT_REASONING","CONTRACT_READY","LOCAL_ACCEPTANCE_PASS","BLOCKED","CANCELLED"],WAIT_REASONING:["CONTRACT_READY","BLOCKED","CANCELLED"],CONTRACT_READY:["BUILDING","BLOCKED","CANCELLED"],LOCAL_ACCEPTANCE_PASS:["WAIT_REVIEW","HUMAN_GATE","DONE","BLOCKED","CANCELLED"],WAIT_REVIEW:["REVIEW_NEED_CHANGE","REVIEW_PASS","BLOCKED","CANCELLED"],REVIEW_NEED_CHANGE:["REPAIRING","BLOCKED","CANCELLED"],REPAIRING:["LOCAL_ACCEPTANCE_PASS","WAIT_REVIEW","BLOCKED","CANCELLED"],REVIEW_PASS:["HUMAN_GATE","DONE","BLOCKED","CANCELLED"],HUMAN_GATE:["BUILDING","DONE","BLOCKED","CANCELLED"],DONE:[],BLOCKED:[],CANCELLED:[]};
const id=(v:unknown):v is string=>typeof v==="string"&&/^[A-Za-z0-9_.-]+$/.test(v); const n=(v:unknown):v is number=>typeof v==="number"&&Number.isInteger(v)&&v>=0; const pid=(v:unknown):v is number=>typeof v==="number"&&Number.isInteger(v)&&v>0; const time=(v:unknown):v is string=>typeof v==="string"&&v.trim()!==""&&Number.isFinite(Date.parse(v));
function validAction(v:unknown):v is ActiveAction { const x=v as Record<string,unknown>; return !!x&&id(x.actionId)&&id(x.semanticRequestId)&&typeof x.validUntil==="string"&&typeof x.startedAt==="string"&&(x.resolvedAt===undefined||typeof x.resolvedAt==="string"); }
function valid(v:unknown):v is TaskState { const x=v as Record<string,unknown>; return !!x&&id(x.taskId)&&id(x.workspaceId)&&n(x.iteration)&&n(x.attempt)&&x.attemptId===`${x.taskId}:i${x.iteration}:a${x.attempt}`&&n(x.reasoningCycle)&&n(x.reviewCycle)&&n(x.revision)&&typeof x.state==="string"&&(TASK_STATES as readonly string[]).includes(x.state)&&typeof x.createdAt==="string"&&typeof x.updatedAt==="string"&&(x.activeAction===undefined||validAction(x.activeAction)); }
function validLock(v:unknown,w:string,t:string):v is TaskStateLock { const x=v as Record<string,unknown>; return !!x&&x.workspaceId===w&&x.taskId===t&&pid(x.ownerPid)&&id(x.ownerSessionMarker)&&time(x.acquiredAt); }
function validLease(v:unknown,w:string):v is WorkspaceMutationLease { const x=v as Record<string,unknown>; return !!x&&x.workspaceId===w&&id(x.taskId)&&id(x.leaseId)&&pid(x.ownerPid)&&id(x.ownerSessionMarker)&&time(x.acquiredAt)&&time(x.heartbeatAt); }
export class TaskStateStore {
 private root:string; private now:()=>Date; private pid:(p:number)=>boolean|undefined;
 constructor(o:TaskStateStoreOptions={}){this.root=path.resolve(o.stateDir??getStateDir(),"tasks");this.now=o.now??(()=>new Date());this.pid=o.pidExists??(p=>{try{process.kill(p,0);return true;}catch(e){return (e as NodeJS.ErrnoException).code==="ESRCH"?false:undefined;}});}
 private wd(w:string){if(!id(w))throw new TaskStateError("INVALID_WORKSPACE_ID");return path.join(this.root,w);} taskFile(w:string,t:string){if(!id(t))throw new TaskStateError("INVALID_TASK_ID");return path.join(this.wd(w),`${t}.json`);} private lock(w:string,t:string){return path.join(this.wd(w),".state-locks",`${t}.lock`);} private lease(w:string){return path.join(this.wd(w),".mutation-lease");}
 createTaskState(workspaceId:string){const taskId=`c2c_${crypto.randomBytes(16).toString("hex")}`,now=this.now().toISOString();const s:TaskState={taskId,workspaceId,iteration:0,attempt:0,attemptId:`${taskId}:i0:a0`,reasoningCycle:0,reviewCycle:0,revision:0,state:"CREATED",createdAt:now,updatedAt:now};this.writeTaskStateAtomic(s);return s;}
 readTaskState(w:string,t:string):ReadTaskState {let raw:string;try{raw=fs.readFileSync(this.taskFile(w,t),"utf8");}catch(e){return (e as NodeJS.ErrnoException).code==="ENOENT"?{status:"NOT_FOUND"}:{status:"IO_ERROR",error:String(e)};}try{const x:unknown=JSON.parse(raw);if(!valid(x))return{status:"CORRUPT",error:"TASK_STATE_SCHEMA_INVALID"};return x.workspaceId===w&&x.taskId===t?{status:"VALID",state:x}:{status:"CORRUPT",error:"TASK_STATE_IDENTITY_MISMATCH"};}catch(e){return{status:"CORRUPT",error:String(e)};}}
 writeTaskStateAtomic(s:TaskState){if(!valid(s))throw new TaskStateError("TASK_STATE_SCHEMA_INVALID");const target=this.taskFile(s.workspaceId,s.taskId);fs.mkdirSync(path.dirname(target),{recursive:true,mode:0o700});const tmp=path.join(path.dirname(target),`.${s.taskId}.${crypto.randomBytes(8).toString("hex")}.tmp`);let fd:number|undefined;try{fd=fs.openSync(tmp,"wx",0o600);fs.writeFileSync(fd,JSON.stringify(s));fs.fsyncSync(fd);fs.closeSync(fd);fd=undefined;fs.renameSync(tmp,target);}finally{if(fd!==undefined)fs.closeSync(fd);try{fs.rmSync(tmp,{force:true});}catch{}}}
 acquireTaskStateLock(w:string,t:string):string{const d=this.lock(w,t);fs.mkdirSync(path.dirname(d),{recursive:true});try{fs.mkdirSync(d);fs.writeFileSync(path.join(d,"lock.json"),JSON.stringify({workspaceId:w,taskId:t,ownerPid:process.pid,ownerSessionMarker:crypto.randomBytes(16).toString("hex"),acquiredAt:this.now().toISOString()} satisfies TaskStateLock),{mode:0o600});return d;}catch(e){if((e as NodeJS.ErrnoException).code==="EEXIST")throw new TaskStateError("TASK_STATE_LOCK_HELD");throw e;}}
 releaseTaskStateLock(lockPath:string):void{fs.rmSync(path.join(lockPath,"lock.json"),{force:true});fs.rmdirSync(lockPath);}
 takeOverStaleTaskStateLock(w:string,t:string,staleMs:number):string{const d=this.lock(w,t);let lock:unknown;try{lock=JSON.parse(fs.readFileSync(path.join(d,"lock.json"),"utf8"));}catch{throw new TaskStateError("MALFORMED_LOCK_METADATA");}if(!validLock(lock,w,t))throw new TaskStateError("MALFORMED_LOCK_METADATA");if(Date.parse(lock.acquiredAt)+staleMs>=this.now().getTime()||this.pid(lock.ownerPid)!==false)throw new TaskStateError("TASK_STATE_LOCK_NOT_STALE");try{fs.renameSync(d,`${d}.stale-${lock.ownerPid}-${Date.parse(lock.acquiredAt)}`);}catch(e){throw new TaskStateError("TASK_STATE_LOCK_RECOVERY_RACE",String(e));}return this.acquireTaskStateLock(w,t);}
 private withLock<T>(w:string,t:string,fn:()=>T){const d=this.acquireTaskStateLock(w,t);try{return fn();}finally{this.releaseTaskStateLock(d);}}
  updateTaskState(w:string,t:string,rev:number,fn:(s:TaskState)=>TaskState){return this.withLock(w,t,()=>{const r=this.readTaskState(w,t);if(r.status!=="VALID")throw new TaskStateError(r.status,"error"in r?r.error:undefined);if(r.state.revision!==rev)throw new TaskStateError("STALE_TASK_STATE");const x=fn({...r.state});if(x.taskId!==t||x.workspaceId!==w)throw new TaskStateError("TASK_IDENTITY_IMMUTABLE");const next={...x,revision:rev+1,attemptId:`${t}:i${x.iteration}:a${x.attempt}`,updatedAt:this.now().toISOString()};this.writeTaskStateAtomic(next);return next;});}
 /** Mutation callers must prove lease ownership before the short CAS lock is acquired. */
 updateTaskStateWithMutationLease(w:string,t:string,owner:MutationLeaseOwner,rev:number,fn:(s:TaskState)=>TaskState){this.requireMutationLeaseOwner(w,t,owner);return this.updateTaskState(w,t,rev,fn);}
 transitionTask(w:string,t:string,r:number,next:TaskStateName){return this.updateTaskState(w,t,r,s=>{if(next==="HUMAN_GATE"&&s.activeAction&&!s.activeAction.resolvedAt)throw new TaskStateError("UNRESOLVED_ACTIVE_ACTION");if(!edges[s.state].includes(next))throw new TaskStateError("ILLEGAL_TASK_TRANSITION");return{...s,state:next};});} isTerminal(s:TaskStateName){return terminal.has(s);}
 private readLease(w:string):WorkspaceMutationLease|null{try{return JSON.parse(fs.readFileSync(path.join(this.lease(w),"lease.json"),"utf8")) as WorkspaceMutationLease;}catch{return null;}}
 acquireWorkspaceMutationLease(w:string,t:string,marker:string){const d=this.lease(w),now=this.now().toISOString(),l:WorkspaceMutationLease={workspaceId:w,taskId:t,leaseId:crypto.randomBytes(16).toString("hex"),ownerPid:process.pid,ownerSessionMarker:marker,acquiredAt:now,heartbeatAt:now};fs.mkdirSync(path.dirname(d),{recursive:true});try{fs.mkdirSync(d);}catch(e){if((e as NodeJS.ErrnoException).code==="EEXIST")throw new TaskStateError("WORKSPACE_MUTATION_LEASE_HELD");throw e;}fs.writeFileSync(path.join(d,"lease.json"),JSON.stringify(l),{mode:0o600});return l;}
 requireMutationLeaseOwner(w:string,t:string,owner:MutationLeaseOwner){const x=this.readLease(w);if(!x||!validLease(x,w)||x.taskId!==t||x.leaseId!==owner.leaseId||x.ownerSessionMarker!==owner.ownerSessionMarker)throw new TaskStateError("MUTATION_LEASE_NOT_OWNED");}
 renewWorkspaceMutationLease(w:string,t:string,owner:MutationLeaseOwner){this.requireMutationLeaseOwner(w,t,owner);const x={...this.readLease(w)!,heartbeatAt:this.now().toISOString()};fs.writeFileSync(path.join(this.lease(w),"lease.json"),JSON.stringify(x));return x;}
 releaseWorkspaceMutationLease(w:string,t:string,owner:MutationLeaseOwner){this.requireMutationLeaseOwner(w,t,owner);fs.rmSync(this.lease(w),{recursive:true});}
 updateTaskStateUnderMutationLease(w:string,t:string,rev:number,owner:MutationLeaseOwner,fn:(s:TaskState)=>TaskState){this.requireMutationLeaseOwner(w,t,owner);return this.updateTaskState(w,t,rev,fn);}
 checkBeforeReplay(state:TaskState, semanticRequestValidUntil:string):ReplayDecision { if(state.activeAction&&!state.activeAction.resolvedAt)return "DENY_UNRESOLVED_ACTIVE_ACTION";return Date.parse(semanticRequestValidUntil)>this.now().getTime()?"ALLOW":"DENY_STALE_SEMANTIC_REQUEST"; }
 beginActiveAction(w:string,t:string,rev:number,owner:MutationLeaseOwner,action:ActiveAction){return this.updateTaskStateUnderMutationLease(w,t,rev,owner,s=>{if(this.checkBeforeReplay(s,action.validUntil)!=="ALLOW")throw new TaskStateError("CHECK_BEFORE_REPLAY_DENIED");return {...s,activeAction:action};});}
 resolveActiveAction(w:string,t:string,rev:number,owner:MutationLeaseOwner,actionId:string){return this.updateTaskStateUnderMutationLease(w,t,rev,owner,s=>{if(!s.activeAction||s.activeAction.actionId!==actionId||s.activeAction.resolvedAt)throw new TaskStateError("ACTIVE_ACTION_NOT_RESOLVABLE");return {...s,activeAction:{...s.activeAction,resolvedAt:this.now().toISOString()}};});}
 assertAtomicReplaceAdmission(w:string){const dir=this.wd(w);fs.mkdirSync(dir,{recursive:true,mode:0o700});const target=path.join(dir,".atomic-replace-admission");const tmp=`${target}.${crypto.randomBytes(8).toString("hex")}.tmp`;try{fs.writeFileSync(target,"old",{mode:0o600});fs.writeFileSync(tmp,"new",{mode:0o600});fs.renameSync(tmp,target);if(fs.readFileSync(target,"utf8")!=="new")throw new Error("replace verification failed");}catch(e){throw new TaskStateError("WINDOWS_ATOMIC_REPLACE_ADMISSION_FAILED",String(e));}finally{try{fs.rmSync(tmp,{force:true});fs.rmSync(target,{force:true});}catch{}}}
 takeOverStaleWorkspaceMutationLease(w:string,t:string,m:string,ms:number){const d=this.lease(w),x=this.readLease(w);if(!x){if(fs.existsSync(d))throw new TaskStateError("MALFORMED_LEASE_METADATA");return this.acquireWorkspaceMutationLease(w,t,m);}if(!validLease(x,w))throw new TaskStateError("MALFORMED_LEASE_METADATA");if(x.taskId!==t)throw new TaskStateError("RECOVERY_REQUIRED");if(Date.parse(x.heartbeatAt)+ms>=this.now().getTime()||this.pid(x.ownerPid)!==false)throw new TaskStateError("LEASE_NOT_STALE");const archive=`${d}.stale.${x.leaseId}.${Date.parse(x.heartbeatAt)}`;try{fs.mkdirSync(archive);fs.renameSync(d,path.join(archive,"lease"));}catch(e){try{if(fs.existsSync(archive)&&fs.readdirSync(archive).length===0)fs.rmdirSync(archive);}catch{}throw new TaskStateError("LEASE_TAKEOVER_RACE",String(e));}return this.acquireWorkspaceMutationLease(w,t,m);}
}

export function isTerminalState(state: TaskStateName): boolean { return terminal.has(state); }

/** Only explicit, read-only command shapes may cross the protected-command boundary. */
export function classifyProtectedCommand(command: unknown): ProtectedCommandDecision {
 if(typeof command!=="string"||!command.trim())return {decision:"DENY",reason:"EMPTY_OR_UNCLASSIFIED"};
 const normalized=command.trim().replace(/\s+/g," ");
 if(/\b(add|amend|apply|checkout|clean|commit|config|merge|mv|push|rebase|reset|restore|rm)\b/i.test(normalized))return {decision:"DENY",reason:"MUTATING_OR_PROTECTED"};
 return /^(git (diff|log|show|status)( |$)|c2c (status|doctor)( |$))/.test(normalized)?{decision:"ALLOW",reason:"READ_ONLY_COMMAND"}:{decision:"DENY",reason:"EMPTY_OR_UNCLASSIFIED"};
}
